### ISSUE TITLE
Question/ Suggestion 

### ISSUE THREAD

**Issue by ghost** [timodejong95/MMM-BluetoothDevices#1]
When connecting your Oral-B toothbrush is there any additional functionality like syncing with your Oral-B me Account like after your done so it’s automatically sync with the Oral-B app then if you do that since I had saw someone made a notification model so as an idea maybe you could add to that too if you would like to add more Oral-B functionality as for Bluetooth connecting headphones or Bluetooth speakers

**Comment by timodejong95** [comment]
Hey super sorry for my late reply, I messed up my notifications.

I get your question, at this point the module is not acting as a hub between the toothbrush and the mobile app, it replaces the app. I can refactor it to be a hub, so at one hand it connects with the toothbrush and on the other hand it fakes the toothbrush so it can connect to the app. I don't have priority to make this because it's intended to replace the app and I think it will take a bit of time.

What are the reasons you are still using the app? Maybe the module does not support the things you want (yet).

Do you got a link to the notification model you are referring too?

**Comment by ghost** [comment]
i can't remember the notification model maybe what i was getting at is sync the data log of where you need to brush while your brushing i like being able to keep a log of everything i do maybe you can find a way to add apple health sync

**Comment by timodejong95** [comment]
Oke I get where your going at. But I think that goes beyond the initial target of this module. I mean it would be a nice extension to this module. And I dont know if the apple health sync is open or that you need an IOS app for it to sync data.
